---
title: "PRSmix test in ECLIPSE"
output:
  html_document:
    toc: true
    toc_float: true
date: "`r format(Sys.time(), '%B %d, %Y')`"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r, message=FALSE, warning=FALSE}
library(data.table)
library(tableone)
library(dplyr)
library(MASS)
library(ggplot2)
library(pROC)
library(ResourceSelection)
library(MatchIt)
```

```{r, message=FALSE, warning=FALSE}
setwd(dirname(rstudioapi::getActiveDocumentContext()$path))
options(bitmapType='cairo')

# import functions 
source("PRSmix_functions.R")
```

```{r}
eclipse_pheno <- fread("path/to/eclipse/pheno.txt",data.table=F)

# all other outcomes
load("path/to/eclipse/more_pheno.rda")

# exacerbation
exac=fread("path/to/eclipse/exacerbations.csv",data.table=F,select=c("GLOBALID","total_exacerbations"))
colnames(exac) <- c("IID", "total_exacerbations")
```

```{r}
# european PRS
ec_ePrs_ratio=readRDS("path/to/ratio_prs.rds")
ec_ePrs_fev1=readRDS("path/to/fev1_prs.rds")

ec_ePrs_fev1=as.data.frame(ec_ePrs_fev1$results.table)
ec_ePrs_fev1=ec_ePrs_fev1[,c("IID","best.pgs")]
ec_ePrs_fev1=setNames(ec_ePrs_fev1,c("IID","FEV1_ePRS"))

ec_ePrs_ratio=as.data.frame(ec_ePrs_ratio$results.table)
ec_ePrs_ratio=ec_ePrs_ratio[,c("IID","best.pgs")]
ec_ePrs_ratio=setNames(ec_ePrs_ratio,c("IID","FF_ePRS"))

# BMI PRS
bmi_prs=fread("path/to/bmi_prs.csv",data.table=F)
colnames(bmi_prs) <- c("IID", "BMI_pgs")

# DL spiro PRS
Cosentino_prs=fread("path/to/Cosentino_prs.csv",data.table=F)
colnames(Cosentino_prs) <- c("IID", "Cosentino_pgs")

# IPF PRS
IPF_prs=fread("path/to/ipf_prs.csv",data.table=F)
colnames(IPF_prs) <- c("IID", "IPF_pgs")

# Smoking PRS
smoking_prs=fread("path/to/smoking_prs.csv",data.table=F)
colnames(smoking_prs) <- c("IID", "smoking_pgs")

# CRP PRS
CRP_prs=fread("path/to/crp_prs.csv",data.table=F)
colnames(CRP_prs) <- c("IID", "CRP_pgs")
```

```{r}
df <- merge(eclipse_pheno, ECcomp, by.x="IID", by.y="sid")

df <- merge(df, exac, by="IID", all.x = TRUE)

df <- merge(df, ec_ePrs_fev1, by="IID")
df <- merge(df, ec_ePrs_ratio, by="IID")
df <- merge(df, bmi_prs, by="IID")
df <- merge(df, Cosentino_prs, by="IID")
df <- merge(df, IPF_prs, by="IID")
df <- merge(df, smoking_prs, by="IID")
df <- merge(df, CRP_prs, by="IID")
```

```{r}
pcs <- paste0("pc",1:5)
covars <- c("age","sex","py","BMI")
```

```{r}
df$copd <- df$caCoStatus - 1
all_pgs_list <- c("FF_ePRS", "FEV1_ePRS", "Cosentino_pgs", "smoking_pgs", "IPF_pgs", "BMI_pgs", "CRP_pgs")

for (prs in all_pgs_list) {
  print(prs)
  df[[prs]] = scale(df[[prs]])
  
  model <- glm(copd ~ df[[prs]], data = df, family = "binomial")
  
  coef <- summary(model)$coefficients[2, 1] 
  p_value <- summary(model)$coefficients[2, 4]
  
  if (p_value <= 0.05) {
    print(paste("p_value:", p_value, "coef:", coef))
    if (coef < 0) {
      df[[prs]] <- df[[prs]] * -1
    }
  } else {
    print("No significant association with copd")
  }
}

# make composite prs
df$prs_composite <- 0.43847 * df$FEV1_ePRS + 0.58833 * df$FF_ePRS
df$prs_composite <- scale(df$prs_composite)
```

```{r}
sapply(df[c(c("FF_ePRS", "FEV1_ePRS", "Cosentino_pgs", "smoking_pgs", "IPF_pgs", "BMI_pgs", "CRP_pgs"), pcs, covars)], function(x) sum(is.na(x)))
outcomes <- c("total_exacerbations", "copd")
sapply(df[outcomes], function(x) sum(is.na(x)))
```

```{r}
# fill na with zero
summary(df$total_exacerbations)
df$total_exacerbations[is.na(df$total_exacerbations)] <- 0
summary(df$total_exacerbations)
```

```{r}
# allVars <- c(covars, "evSmoke", "preFev", "preRat", "total_exacerbations")
allVars <- c("age", "sex", "SmokCigNow", "py", "BMI", "FEV1pp_utah", "FEV1_FVC_utah", "copd", "Exacerbation_Frequency")
catVars <- c("sex", "SmokCigNow", "copd")
table1 <- CreateTableOne(data = df, vars = allVars, factorVars = catVars)
table1_output <- print(table1, showAllLevels = TRUE)

write.table(table1_output, "data/Table1_demographics_ECLIPSE.txt", sep = "\t", row.names = TRUE, quote = FALSE)
```

# Use weights from PRSmix trained in COPD NHW to weigh PRSs in eclipse
```{r}
# get mix_prs_copd
df <- scale_PRSmix_other_coh(df, outcome_name_copd="copd", coh="cgNhw")
```

# Table3_PRSs_copd: COPD predicted by single PRSs and PRSmix
```{r message=FALSE, warning=FALSE}
Table3_PRSs_copd <- call_model_other_coh(df, outcome_name_copd="copd", outcome_name_other_coh="copd", pcs, covars, model_type = "binomial", adjustment = NULL, coh = "cgNhw", additional_prs = "prs_composite")

prs_order <- c("FF_ePRS", "FEV1_ePRS", "Cosentino_pgs", "smoking_pgs", "IPF_pgs", "BMI_pgs", "CRP_pgs", "mix_prs_copd", "prs_composite")

Table3_PRSs_copd <- Table3_PRSs_copd[order(match(Table3_PRSs_copd$prs, prs_order)), ]

write.table(Table3_PRSs_copd, "data/Table3_PRSs_copd_ECLIPSE.txt", sep = "\t", row.names = FALSE, quote = FALSE)
Table3_PRSs_copd <- Table3_PRSs_copd %>%  mutate_if(is.numeric, signif, digits=3)
DT::datatable(Table3_PRSs_copd, rownames = FALSE)
```

# Table4_PRSs_exacerbations: exacerbation predicted by single PRSs and PRSmix
```{r message=FALSE, warning=FALSE}
Table4_PRSs_exacerbations <- call_model_other_coh(df, outcome_name_copd="copd", outcome_name_other_coh="total_exacerbations", pcs, covars, model_type = "nb", adjustment = "offset(log(days_followed/365))", coh = "cgNhw", additional_prs = "prs_composite")

Table4_PRSs_exacerbations <- Table4_PRSs_exacerbations[order(match(Table4_PRSs_exacerbations$prs, prs_order)), ]

write.table(Table4_PRSs_exacerbations, "data/Table4_PRSs_exacerbations_ECLIPSE.txt", sep = "\t", row.names = FALSE, quote = FALSE)
Table4_PRSs_exacerbations <- Table4_PRSs_exacerbations %>% mutate_if(is.numeric, signif, digits=3)
DT::datatable(Table4_PRSs_exacerbations, rownames = FALSE)
```

## ROC of COPD predicted by PRSmix vs FF PRS
```{r fig.width=7, fig.height=5, message=FALSE, warning=FALSE}
df_copd_complete <- df[complete.cases(df[, "copd"]), ]
outcome_binary <- "copd"

# print DeLong p-values for PRS-mix vs FF PRS
copd_roc_out <- compare_roc_5_models(df_copd_complete, outcome_binary, mix_prs="mix_prs_copd", prs_to_compare="FF_ePRS", pcs, covars, adjustment=NULL, plot_title = "COPD predicted by PRSmix vs. FEV1/FVC PRS in ECLIPSE")

DT::datatable(copd_roc_out$auc_table)
DT::datatable(copd_roc_out$pval_table)
```

## ROC of exacerbations predicted by PRSmix vs FF PRS
```{r fig.width=7, fig.height=5, message=FALSE, warning=FALSE}
df_exac_complete <- df[complete.cases(df[, c("total_exacerbations", "days_followed")]), ]

outcome <- "total_exacerbations"
outcome_binary <- paste0(outcome, "_binary")
df_exac_complete[[outcome_binary]] <- ifelse(df_exac_complete[[outcome]] >= 2, 1, 0)

# print DeLong p-values for PRS-mix vs FF PRS
exac_roc_out <- compare_roc_5_models(df_exac_complete, outcome_binary, mix_prs="mix_prs_copd", prs_to_compare="FF_ePRS", pcs, covars, adjustment="offset(log(days_followed/365))", plot_title = "Exacerbations predicted by PRSmix vs. FEV1/FVC PRS in ECLIPSE")

DT::datatable(exac_roc_out$auc_table)
DT::datatable(exac_roc_out$pval_table)
```

# incident rate ratio
```{r}
youden_threshold_copd <- 0.3752354

df$youden_group <- ifelse(df$mix_prs_copd > youden_threshold_copd, 1, 0)
table(df$youden_group)
```

```{r}
# get propensity score
formula_str <- paste0("youden_group ~ ", paste0(c(covars), collapse = " + "))

# propensity score matching 
m.out <- matchit(as.formula(formula_str), 
                 data = df, 
                 method = "nearest")

matched_df <- match.data(m.out)
```

```{r}
# calculate irr
formula_str <- paste0("total_exacerbations", " ~ youden_group + ", paste0(c(pcs), collapse = " + "))
irr_model <- glm.nb(as.formula(formula_str), data = matched_df)
summary(irr_model)
```

```{r}
cor(df$BMI, df$BMI_pgs)
```

