---
title: "Asscociation of metaxcan proteins in COPD somascan with COPD and exacerbations"
output:
  html_document:
    toc: true
    toc_float: true
date: "`r format(Sys.time(), '%B %d, %Y')`"
---
```{r}
library(data.table)
library(tableone)
library(MASS)
library(ggplot2)
library(dplyr)
library(tidyr)

options(bitmapType='cairo')
```

# load data
```{r}
somascan5k <- read.table("path/to/somascan_data.txt", sep="\t", header = TRUE)

somascan5k <- somascan5k %>%
  mutate(across(-sid, scale))
```

```{r}
metadat5k <- read.table("path/to/somascan_metadata.txt", sep='\t', header = TRUE, quote = "", fill = TRUE)

mapping_df <- metadat5k[, c("EnsemblGeneID", "UniProt", "EntrezGeneSymbol")]

mapping_df$EnsemblGeneList <- strsplit(as.character(mapping_df$EnsemblGeneID), "\\|")
mapping_df$EntrezGeneList <- strsplit(as.character(mapping_df$EntrezGeneSymbol), "\\|")

print(nrow(mapping_df))
mapping_df<-unique(mapping_df)
print(nrow(mapping_df))

# dups in somascan
sapply(mapping_df, function(x) sum(duplicated(x)))
```

```{r}
# check if IDs match up
metadat5k_ids <- as.character(metadat5k$seqID)
somascan5k_ids <- colnames(somascan5k)[-1]
somascan5k_ids <- substring(somascan5k_ids, 2)

all(metadat5k_ids == somascan5k_ids)

# replace colnames with uniprot ID
new_columns <- c("sid", metadat5k$UniProt)
colnames(somascan5k) <- new_columns
```

```{r}
# pheno_p1 and pheno_p2
miniGridDir="path/to/"
load(paste0(miniGridDir,"miniCgGrid_datasets.Rdata"))

# people with somascan
pheno_p2 <- pheno_p2[pheno_p2$sid %in% somascan5k$sid, ]

# make binary copd variable
pheno_p2$copd <- ifelse(pheno_p2$FEV1_FVC_post_P2 < 0.7 & pheno_p2$fev1_pp_gli_global_P2 < 80, 1,
                      ifelse(pheno_p2$FEV1_FVC_post_P2 >= 0.7 & pheno_p2$fev1_pp_gli_global_P2 >= 80, 0, NA))

# ccenter
ccenter <- read.table("path/to/ccenter.txt", sep="\t", header = TRUE, quote = "", fill = TRUE)[, c("sid", "ccenter_P2")]
pheno_p2 <- merge(pheno_p2, ccenter, all.x=TRUE)

# fill pack years with 0 if smoking is 0
pheno_p2$ATS_PackYears_P2[is.na(pheno_p2$ATS_PackYears_P2) & pheno_p2$SmokCigNow_P2 == 0] <- 0

covars <- c("Age_P2","gender","race","ATS_PackYears_P2", "ccenter_P2", "Exacerbation_Frequency_P2")

sapply(pheno_p2[c(covars, "total_days_since_P2")], function(x) sum(is.na(x)))
pheno_p2 <- pheno_p2[complete.cases(pheno_p2[, c(covars, "total_days_since_P2")]), ]

adj_p_thres <- 0.1
p_thres <- 0.05

# only one in this group, causes convergence issue
pheno_p2 <- pheno_p2 %>% filter(ccenter_P2 != "group_N")
```

# table one
```{r}
pheno_p2$exacerbation_rate = pheno_p2$total_Net_Exacerbations / pheno_p2$total_days_since_P2 * 365

allVars <- c("Age_P2", "gender", "race", "SmokCigNow_P2", "ATS_PackYears_P2", "fev1_pp_gli_global_P2", "FEV1_FVC_post_P2", "exacerbation_rate", "copd")
catVars <- c("gender", "race", "SmokCigNow_P2", "copd")
table1 <- CreateTableOne(data = pheno_p2, vars = allVars, factorVars = catVars)
table1_output <- print(table1, showAllLevels = TRUE)

write.table(table1_output, "data/TableS1_demographics_COPDGene_somascan_new.txt", sep = "\t", row.names = TRUE, quote = FALSE)
```

# functions
```{r}
call_model <- function(df, outcome_name, top_genes, covars, adjustment=NULL, model_type) {
  results <- data.frame(gene = character(), beta = numeric(), ci_lower = numeric(), ci_upper = numeric(), beta_ci = character(), pval = numeric(), stringsAsFactors = FALSE)

  for (gene in top_genes) {
    gene <- ifelse(grepl("\\|", gene), paste0("`", gene, "`"), gene)

    formula_components <- c(gene, covars, adjustment)
    formula_str <- paste0(outcome_name, " ~ ", paste0(formula_components, collapse = " + "))
    
    if (model_type == "nb") {
      model <- glm.nb(as.formula(formula_str), data = df)
    } else if (model_type == "binomial") {
    model <- glm(as.formula(formula_str), data = df, family = binomial())
    }

    beta <- coef(model)[gene]
    ci <- confint(model, gene, level = 0.95)
    beta_ci <- sprintf("%.3f (%.3f, %.3f)", beta, ci[1], ci[2])
    pval <- summary(model)$coefficients[gene, 4]
    results <- rbind(results, data.frame(gene = gene, beta = beta, ci_lower = ci[1], ci_upper = ci[2], beta_ci = beta_ci, pval = pval))
  }
  return(results)
}
```

```{r}
map_genes <- function(metaxcan_df, mapping_df) {
  
  metaxcan_df$UniProt <- NA
  metaxcan_df$matched_symbol <- NA
  
  for (i in seq_len(nrow(metaxcan_df))) {
    gene <- metaxcan_df$gene[i]
    gene_name <- metaxcan_df$gene_name[i]
    
    # match by ensembl id 
    ensembl_match <- sapply(mapping_df$EnsemblGeneList, function(ids) gene %in% ids)
    if (any(ensembl_match)) {
      row_idx <- which(ensembl_match)[1]  # take the first match
      metaxcan_df$UniProt[i] <- mapping_df$UniProt[row_idx]
      next
    }
    
    # If no match in ensembl id, check gene name
    entrez_match <- sapply(mapping_df$EntrezGeneList, function(symbols) gene_name %in% symbols)
    if (any(entrez_match)) {
      row_idx <- which(entrez_match)[1]  # take the first match
      metaxcan_df$UniProt[i] <- mapping_df$UniProt[row_idx]
    }
  }
  return(metaxcan_df)
}
```

# BMI
```{r}
bmi_metaxcan <- read.csv("path/to/bmi_SPrediXcan_results.csv")

bmi_metaxcan <- bmi_metaxcan %>%
  distinct(gene, .keep_all = TRUE) %>%
  mutate(adj_p = p.adjust(pvalue, method = "BH")) %>%
  filter(adj_p < adj_p_thres)
print(nrow(bmi_metaxcan))

# map to uniprot id 
bmi_metaxcan <- map_genes(bmi_metaxcan, mapping_df)
bmi_top_genes_intersect <- unique(bmi_metaxcan$UniProt)
print(length(bmi_top_genes_intersect))

# this only selects the first in dups
somascan_filtered_bmi <- somascan5k[, c("sid", bmi_top_genes_intersect)]

# merge with pheno
somascan_pheno_bmi <- merge(somascan_filtered_bmi, pheno_p2, by = "sid")
```

```{r, eval=FALSE}
bmi_genes_exac_adj_copd <- call_model(df=somascan_pheno_bmi, outcome_name='total_Net_Exacerbations', top_genes=bmi_top_genes_intersect, covars=covars, adjustment='copd + offset(log(total_days_since_P2/365))', model_type="nb")

bmi_genes_exac_adj_copd_sig <- bmi_genes_exac_adj_copd %>%
  mutate(adj_p=p.adjust(pval,method = "BH"))  %>% 
  # filter(adj_p < adj_p_thres) %>% 
  filter(pval < p_thres) %>%
  merge(mapping_df[, c("UniProt", "EntrezGeneSymbol")], by.x="gene", by.y="UniProt") %>% 
  arrange(pval)

DT::datatable(bmi_genes_exac_adj_copd_sig[, c("EntrezGeneSymbol", "beta_ci", "pval", "adj_p")], rownames = FALSE)

write.table(bmi_genes_exac_adj_copd_sig, file = "path/to/bmi_exac_signif_genes_adj_copd_adj_p_log_time.txt", sep = "\t", row.names = FALSE, quote = FALSE)
```

```{r}
bmi_genes_exac_adj_copd_sig <- read.table("path/to/bmi_exac_signif_genes_adj_copd_adj_p_log_time.txt", sep = "\t", header = TRUE)
DT::datatable(bmi_genes_exac_adj_copd_sig[, c("EntrezGeneSymbol", "beta_ci", "pval", "adj_p")], rownames = FALSE)
```


```{r, fig.height=10, fig.width=8}
bmi_genes_exac_adj_copd_sig$EntrezGeneSymbol <- factor(bmi_genes_exac_adj_copd_sig$EntrezGeneSymbol, levels = bmi_genes_exac_adj_copd_sig$EntrezGeneSymbol)
bmi_forest_plot <- ggplot(bmi_genes_exac_adj_copd_sig %>% filter(adj_p<adj_p_thres), aes(x = EntrezGeneSymbol, y = beta)) +
  geom_point(size = 1) +
  geom_errorbar(aes(ymin = ci_lower, ymax = ci_upper), width = 0.2) +
  coord_flip() +
  ylim(c(-0.4, 0.4)) +
  labs(x = "Gene", y = "Beta with 95% CI", title = "Associations of top BMI genes with exacerbations in COPDGene") +
  theme_minimal()
bmi_forest_plot

ggsave("plots/bmi_forest_plot_cg_log_time.pdf", plot = bmi_forest_plot, device = "pdf", height = 10, width = 8)
ggsave("plots/bmi_forest_plot_cg_log_time.jpg", plot = bmi_forest_plot, height = 10, width = 8, dpi = 300)
```

# FEV1
```{r}
fev1_metaxcan <- read.csv("path/to/fev1_SPrediXcan_results.csv")
fev1_metaxcan <- fev1_metaxcan %>%
  distinct(gene, .keep_all = TRUE) %>%
  mutate(adj_p = p.adjust(pvalue, method = "BH")) %>%
  filter(adj_p < adj_p_thres)
print(nrow(fev1_metaxcan))
```

```{r}
fev1_metaxcan <- map_genes(fev1_metaxcan, mapping_df)
fev1_top_genes_intersect <- unique(fev1_metaxcan$UniProt)
print(length(fev1_top_genes_intersect))

somascan_filtered_fev1 <- somascan5k[, c("sid", fev1_top_genes_intersect)]

somascan_pheno_fev1 <- merge(somascan_filtered_fev1, pheno_p2, by = "sid")
```

```{r, eval=FALSE}
fev1_genes_exac_adj_copd <- call_model(df=somascan_pheno_fev1, outcome_name='total_Net_Exacerbations', top_genes=fev1_top_genes_intersect, covars=covars, adjustment='copd + offset(log(total_days_since_P2/365))', model_type="nb")

fev1_genes_exac_adj_copd_sig <- fev1_genes_exac_adj_copd %>%
  mutate(adj_p=p.adjust(pval,method = "BH"))  %>% 
  filter(pval < p_thres) %>%
  merge(mapping_df[, c("UniProt", "EntrezGeneSymbol")], by.x="gene", by.y="UniProt") %>% 
  arrange(pval)

DT::datatable(fev1_genes_exac_adj_copd_sig[, c("EntrezGeneSymbol", "beta_ci", "pval", "adj_p")], rownames = FALSE)

write.table(fev1_genes_exac_adj_copd_sig, file = "path/to/fev1_exac_signif_genes_adj_copd_adj_p_log_time.txt", sep = "\t", row.names = FALSE, quote = FALSE)
```

```{r}
fev1_genes_exac_adj_copd_sig <- read.table("path/to/fev1_exac_signif_genes_adj_copd_adj_p_log_time.txt", sep = "\t", header = TRUE)
DT::datatable(fev1_genes_exac_adj_copd_sig[, c("EntrezGeneSymbol", "beta_ci", "pval", "adj_p")], rownames = FALSE)
```

```{r, fig.height=10, fig.width=8}
fev1_genes_exac_adj_copd_sig$EntrezGeneSymbol <- factor(fev1_genes_exac_adj_copd_sig$EntrezGeneSymbol, levels = fev1_genes_exac_adj_copd_sig$EntrezGeneSymbol)

fev1_forest_plot <- ggplot(fev1_genes_exac_adj_copd_sig %>% filter(adj_p<adj_p_thres), aes(x = EntrezGeneSymbol, y = beta)) +
  geom_point(size = 1) +
  geom_errorbar(aes(ymin = ci_lower, ymax = ci_upper), width = 0.2) +
  coord_flip() +
  ylim(c(-0.3, 0.3)) +
  labs(x = "Gene", y = "Beta with 95% CI", title = "Associations of top FEV1 genes with exacerbations in COPDGene") +
  theme_minimal()
fev1_forest_plot

ggsave("plots/fev1_forest_plot_cg_log_time.pdf", plot = fev1_forest_plot, device = "pdf", height = 10, width = 8)
ggsave("plots/fev1_forest_plot_cg_log_time.jpg", plot = fev1_forest_plot, height = 10, width = 8, dpi = 300)
```

# FF
```{r}
ff_metaxcan <- read.csv("path/to/ff_SPrediXcan_results.csv")
ff_metaxcan <- ff_metaxcan %>%
  distinct(gene, .keep_all = TRUE) %>%
  mutate(adj_p = p.adjust(pvalue, method = "BH")) %>%
  filter(adj_p < adj_p_thres)
print(nrow(ff_metaxcan))

ff_metaxcan <- map_genes(ff_metaxcan, mapping_df)
ff_top_genes_intersect <- unique(ff_metaxcan$UniProt)
print(length(ff_top_genes_intersect))

somascan_filtered_ff <- somascan5k[, c("sid", ff_top_genes_intersect)]

somascan_pheno_ff <- merge(somascan_filtered_ff, pheno_p2, by = "sid")
```

```{r, eval=FALSE}
ff_genes_exac_adj_copd <- call_model(df=somascan_pheno_ff, outcome_name='total_Net_Exacerbations', top_genes=ff_top_genes_intersect, covars=covars, adjustment='copd + offset(log(total_days_since_P2/365))', model_type="nb")

ff_genes_exac_adj_copd_sig <- ff_genes_exac_adj_copd %>%
  mutate(adj_p=p.adjust(pval,method = "BH"))  %>% 
  filter(pval < p_thres) %>%
  merge(mapping_df[, c("UniProt", "EntrezGeneSymbol")], by.x="gene", by.y="UniProt") %>% 
  arrange(pval)

DT::datatable(ff_genes_exac_adj_copd_sig[, c("EntrezGeneSymbol", "beta_ci", "pval", "adj_p")], rownames = FALSE)

write.table(ff_genes_exac_adj_copd_sig, file = "path/to/ff_exac_signif_genes_adj_copd_adj_p_log_time.txt", sep = "\t", row.names = FALSE, quote = FALSE)
```

```{r}
ff_genes_exac_adj_copd_sig <- read.table("path/to/ff_exac_signif_genes_adj_copd_adj_p_log_time.txt", sep = "\t", header = TRUE)
DT::datatable(ff_genes_exac_adj_copd_sig[, c("EntrezGeneSymbol", "beta_ci", "pval", "adj_p")], rownames = FALSE)
```

```{r, fig.height=8, fig.width=8}
ff_genes_exac_adj_copd_sig$EntrezGeneSymbol <- factor(ff_genes_exac_adj_copd_sig$EntrezGeneSymbol, levels = ff_genes_exac_adj_copd_sig$EntrezGeneSymbol)

ff_forest_plot <- ggplot(ff_genes_exac_adj_copd_sig %>% filter(adj_p<adj_p_thres), aes(x = EntrezGeneSymbol, y = beta)) +
  geom_point(size = 1) +
  geom_errorbar(aes(ymin = ci_lower, ymax = ci_upper), width = 0.2) +
  coord_flip() +
  ylim(c(-0.3, 0.3)) +
  labs(x = "Gene", y = "Beta with 95% CI", title = "Associations of top ratio genes with exacerbations in COPDGene") +
  theme_minimal()
ff_forest_plot

ggsave("plots/ff_forest_plot_cg_log_time.pdf", plot = ff_forest_plot, device = "pdf", height = 8, width = 8)
ggsave("plots/ff_forest_plot_cg_log_time.jpg", plot = ff_forest_plot, height = 8, width = 8, dpi = 300)
```



# Smoking
```{r}
smoking_metaxcan <- read.csv("path/to/smoking_SPrediXcan_results.csv")
smoking_metaxcan <- smoking_metaxcan %>%
  distinct(gene, .keep_all = TRUE) %>%
  mutate(adj_p = p.adjust(pvalue, method = "BH")) %>%
  filter(adj_p < adj_p_thres)
print(nrow(smoking_metaxcan))

smoking_metaxcan <- map_genes(smoking_metaxcan, mapping_df)
smoking_top_genes_intersect <- unique(smoking_metaxcan$UniProt)
print(length(smoking_top_genes_intersect))

somascan_filtered_smoking <- somascan5k[, c("sid", smoking_top_genes_intersect)]

somascan_pheno_smoking <- merge(somascan_filtered_smoking, pheno_p2, by = "sid")
```


```{r, eval=FALSE}
smoking_genes_exac_adj_copd <- call_model(df=somascan_pheno_smoking, outcome_name='total_Net_Exacerbations', top_genes=smoking_top_genes_intersect, covars=covars, adjustment='copd + offset(log(total_days_since_P2/365))', model_type="nb")

smoking_genes_exac_adj_copd_sig <- smoking_genes_exac_adj_copd %>%
  mutate(adj_p=p.adjust(pval,method = "BH"))  %>% 
  filter(pval < p_thres) %>%
  merge(mapping_df[, c("UniProt", "EntrezGeneSymbol")], by.x="gene", by.y="UniProt") %>% 
  arrange(pval)

DT::datatable(smoking_genes_exac_adj_copd_sig[, c("EntrezGeneSymbol", "beta_ci", "pval", "adj_p")], rownames = FALSE)

write.table(smoking_genes_exac_adj_copd_sig, file = "path/to/smoking_exac_signif_genes_adj_copd_adj_p_log_time.txt", sep = "\t", row.names = FALSE, quote = FALSE)
```

```{r}
smoking_genes_exac_adj_copd_sig <- read.table("path/to/smoking_exac_signif_genes_adj_copd_adj_p_log_time.txt", sep = "\t", header = TRUE)
DT::datatable(smoking_genes_exac_adj_copd_sig[, c("EntrezGeneSymbol", "beta_ci", "pval", "adj_p")], rownames = FALSE)
```

```{r, fig.height=4, fig.width=8}
smoking_genes_exac_adj_copd_sig$EntrezGeneSymbol <- factor(smoking_genes_exac_adj_copd_sig$EntrezGeneSymbol, levels = smoking_genes_exac_adj_copd_sig$EntrezGeneSymbol)

smoking_forest_plot <- ggplot(smoking_genes_exac_adj_copd_sig %>% filter(adj_p<adj_p_thres), aes(x = EntrezGeneSymbol, y = beta)) +
  geom_point(size = 1) +
  geom_errorbar(aes(ymin = ci_lower, ymax = ci_upper), width = 0.2) +
  coord_flip() +
  ylim(c(-0.25, 0.25)) +
  labs(x = "Gene", y = "Beta with 95% CI", title = "Associations of top smoking genes with exacerbations in COPDGene") +
  theme_minimal()
smoking_forest_plot

ggsave("plots/smoking_forest_plot_cg_log_time.pdf", plot = smoking_forest_plot, device = "pdf", height = 4, width = 8)
ggsave("plots/smoking_forest_plot_cg_log_time.jpg", plot = smoking_forest_plot, height = 4, width = 8, dpi = 300)
```



# IPF
```{r}
ipf_metaxcan <- read.csv("path/to/ipf_SPrediXcan_results.csv")
ipf_metaxcan <- ipf_metaxcan %>%
  distinct(gene, .keep_all = TRUE) %>%
  mutate(adj_p = p.adjust(pvalue, method = "BH")) %>%
  filter(adj_p < adj_p_thres)
print(nrow(ipf_metaxcan))

ipf_metaxcan <- map_genes(ipf_metaxcan, mapping_df)
ipf_top_genes_intersect <- unique(ipf_metaxcan$UniProt)
print(length(ipf_top_genes_intersect))

somascan_filtered_ipf <- somascan5k[, c("sid", ipf_top_genes_intersect)]

somascan_pheno_ipf <- merge(somascan_filtered_ipf, pheno_p2, by = "sid")
```

```{r, eval=FALSE}
ipf_genes_exac_adj_copd <- call_model(df=somascan_pheno_ipf, outcome_name='total_Net_Exacerbations', top_genes=ipf_top_genes_intersect, covars=covars, adjustment='copd + offset(log(total_days_since_P2/365))', model_type="nb")

ipf_genes_exac_adj_copd_sig <- ipf_genes_exac_adj_copd %>%
  mutate(adj_p=p.adjust(pval,method = "BH"))  %>% 
  filter(pval < p_thres) %>%
  merge(mapping_df[, c("UniProt", "EntrezGeneSymbol")], by.x="gene", by.y="UniProt") %>% 
  arrange(pval)

DT::datatable(ipf_genes_exac_adj_copd_sig[, c("EntrezGeneSymbol", "beta_ci", "pval", "adj_p")], rownames = FALSE)

write.table(ipf_genes_exac_adj_copd_sig, file = "path/to/ipf_exac_signif_genes_adj_copd_adj_p_log_time.txt", sep = "\t", row.names = FALSE, quote = FALSE)
```

```{r}
ipf_genes_exac_adj_copd_sig <- read.table("path/to/ipf_exac_signif_genes_adj_copd_adj_p_log_time.txt", sep = "\t", header = TRUE)
DT::datatable(ipf_genes_exac_adj_copd_sig[, c("EntrezGeneSymbol", "beta_ci", "pval", "adj_p")], rownames = FALSE)
```

```{r, fig.height=4, fig.width=8}
ipf_genes_exac_adj_copd_sig$EntrezGeneSymbol <- factor(ipf_genes_exac_adj_copd_sig$EntrezGeneSymbol, levels = ipf_genes_exac_adj_copd_sig$EntrezGeneSymbol)

ipf_forest_plot <- ggplot(ipf_genes_exac_adj_copd_sig %>% filter(adj_p<adj_p_thres), aes(x = EntrezGeneSymbol, y = beta)) +
  geom_point(size = 1) +
  geom_errorbar(aes(ymin = ci_lower, ymax = ci_upper), width = 0.2) +
  coord_flip() +
  ylim(c(-0.25, 0.25)) +
  labs(x = "Gene", y = "Beta with 95% CI", title = "Associations of top IPF genes with exacerbations in COPDGene") +
  theme_minimal()
ipf_forest_plot

ggsave("plots/ipf_forest_plot_cg_log_time.pdf", plot = ipf_forest_plot, device = "pdf", height = 4, width = 8)
ggsave("plots/ipf_forest_plot_cg_log_time.jpg", plot = ipf_forest_plot, height = 4, width = 8, dpi = 300)
```


# DL spiro
```{r}
cosentino_metaxcan <- read.csv("path/to/Cosentino_SPrediXcan_results.csv")
cosentino_metaxcan <- cosentino_metaxcan %>%
  distinct(gene, .keep_all = TRUE) %>%
  mutate(adj_p = p.adjust(pvalue, method = "BH")) %>%
  filter(adj_p < adj_p_thres)
print(nrow(cosentino_metaxcan))

cosentino_metaxcan <- map_genes(cosentino_metaxcan, mapping_df)
cosentino_top_genes_intersect <- unique(cosentino_metaxcan$UniProt)
print(length(cosentino_top_genes_intersect))

somascan_filtered_cosentino <- somascan5k[, c("sid", cosentino_top_genes_intersect)]

somascan_pheno_cosentino <- merge(somascan_filtered_cosentino, pheno_p2, by = "sid")
```

```{r, eval=FALSE}
cosentino_genes_exac_adj_copd <- call_model(df=somascan_pheno_cosentino, outcome_name='total_Net_Exacerbations', top_genes=cosentino_top_genes_intersect, covars=covars, adjustment='copd + offset(log(total_days_since_P2/365))', model_type="nb")

cosentino_genes_exac_adj_copd_sig <- cosentino_genes_exac_adj_copd %>%
  mutate(adj_p=p.adjust(pval,method = "BH"))  %>% 
  filter(pval < p_thres) %>%
  merge(mapping_df[, c("UniProt", "EntrezGeneSymbol")], by.x="gene", by.y="UniProt") %>% 
  arrange(pval)

DT::datatable(cosentino_genes_exac_adj_copd_sig[, c("EntrezGeneSymbol", "beta_ci", "pval", "adj_p")], rownames = FALSE)

write.table(cosentino_genes_exac_adj_copd_sig, file = "path/to/cosentino_exac_signif_genes_adj_copd_adj_p_log_time.txt", sep = "\t", row.names = FALSE, quote = FALSE)
```

```{r}
cosentino_genes_exac_adj_copd_sig <- read.table("path/to/cosentino_exac_signif_genes_adj_copd_adj_p_log_time.txt", sep = "\t", header = TRUE)
DT::datatable(cosentino_genes_exac_adj_copd_sig[, c("EntrezGeneSymbol", "beta_ci", "pval", "adj_p")], rownames = FALSE)
```

```{r, fig.height=4, fig.width=8}
cosentino_genes_exac_adj_copd_sig$EntrezGeneSymbol <- factor(cosentino_genes_exac_adj_copd_sig$EntrezGeneSymbol, levels = cosentino_genes_exac_adj_copd_sig$EntrezGeneSymbol)

cosentino_forest_plot <- ggplot(cosentino_genes_exac_adj_copd_sig %>% filter(adj_p<adj_p_thres), aes(x = EntrezGeneSymbol, y = beta)) +
  geom_point(size = 1) +
  geom_errorbar(aes(ymin = ci_lower, ymax = ci_upper), width = 0.2) +
  coord_flip() +
  ylim(c(-0.3, 0.3)) +
  labs(x = "Gene", y = "Beta with 95% CI", title = "Associations of top Cosentino et al. genes with exacerbations in COPDGene") +
  theme_minimal()
cosentino_forest_plot

ggsave("plots/cosentino_forest_plot_cg_log_time.pdf", plot = cosentino_forest_plot, device = "pdf", height = 4, width = 8)
ggsave("plots/cosentino_forest_plot_cg_log_time.jpg", plot = cosentino_forest_plot, height = 4, width = 8, dpi = 300)
```



# CRP
```{r}
CRP_metaxcan <- read.csv("path/to/CRP_SPrediXcan_results.csv")
CRP_metaxcan <- CRP_metaxcan %>%
  distinct(gene, .keep_all = TRUE) %>%
  mutate(adj_p = p.adjust(pvalue, method = "BH")) %>%
  filter(adj_p < adj_p_thres)
print(nrow(CRP_metaxcan))

CRP_metaxcan <- map_genes(CRP_metaxcan, mapping_df)
CRP_top_genes_intersect <- unique(CRP_metaxcan$UniProt)
print(length(CRP_top_genes_intersect))

somascan_filtered_CRP <- somascan5k[, c("sid", CRP_top_genes_intersect)]

somascan_pheno_CRP <- merge(somascan_filtered_CRP, pheno_p2, by = "sid")
```

```{r, eval=FALSE}
CRP_genes_exac_adj_copd <- call_model(df=somascan_pheno_CRP, outcome_name='total_Net_Exacerbations', top_genes=CRP_top_genes_intersect, covars=covars, adjustment='copd + offset(log(total_days_since_P2/365))', model_type="nb")

CRP_genes_exac_adj_copd_sig <- CRP_genes_exac_adj_copd %>%
  mutate(adj_p=p.adjust(pval,method = "BH"))  %>% 
  filter(pval < p_thres) %>%
  merge(mapping_df[, c("UniProt", "EntrezGeneSymbol")], by.x="gene", by.y="UniProt") %>% 
  arrange(pval)

DT::datatable(CRP_genes_exac_adj_copd_sig[, c("EntrezGeneSymbol", "beta_ci", "pval", "adj_p")], rownames = FALSE)

write.table(CRP_genes_exac_adj_copd_sig, file = "path/to/CRP_exac_signif_genes_adj_copd_adj_p_log_time.txt", sep = "\t", row.names = FALSE, quote = FALSE)
```

```{r}
CRP_genes_exac_adj_copd_sig <- read.table("path/to/CRP_exac_signif_genes_adj_copd_adj_p_log_time.txt", sep = "\t", header = TRUE)
DT::datatable(CRP_genes_exac_adj_copd_sig[, c("EntrezGeneSymbol", "beta_ci", "pval", "adj_p")], rownames = FALSE)
```

```{r, fig.height=6, fig.width=8}
CRP_genes_exac_adj_copd_sig$EntrezGeneSymbol <- factor(CRP_genes_exac_adj_copd_sig$EntrezGeneSymbol, levels = CRP_genes_exac_adj_copd_sig$EntrezGeneSymbol)

CRP_forest_plot <- ggplot(CRP_genes_exac_adj_copd_sig %>% filter(adj_p<adj_p_thres), aes(x = EntrezGeneSymbol, y = beta)) +
  geom_point(size = 1) +
  geom_errorbar(aes(ymin = ci_lower, ymax = ci_upper), width = 0.2) +
  coord_flip() +
  ylim(c(-0.3, 0.3)) +
  labs(x = "Gene", y = "Beta with 95% CI", title = "Associations of top CRP genes with exacerbations in COPDGene") +
  theme_minimal()
CRP_forest_plot

ggsave("plots/CRP_forest_plot_cg_log_time.pdf", plot = CRP_forest_plot, device = "pdf", height = 6, width = 8)
ggsave("plots/CRP_forest_plot_cg_log_time.jpg", plot = CRP_forest_plot, height = 6, width = 8, dpi = 300)
```